### ISSUE TITLE
Windows compatibility for .lookUp

### ISSUE THREAD

**Issue by operatino** [sakren/node-fs-finder#9]
Hi,

I'm trying to run simple search with `lookUp` on Windows - `Finder.in(dir).lookUp(3).findFiles('5.log')`, but Node process stops on the execution and falls into dead lock.

Same script is working on same project on OSx, I've tryed normalizing start dir to use backslashes on Windows but it does not help.

Do you support windows env?

**Comment by operatino** [comment]
Regular finder `Finder.in(dir).findFiles('something')` is functioning well, I also noticed that you normalize windows paths. So the problem is only in `.lookUp()`.

My env - Windows 7, x64. Node v0.12.2.

**Comment by sakren** [comment]
Hello and thanks for your report.

I've never tried Finder at windows, but I thought that it would work (and thats the problem). Unfortunately I also don't have any windows machine (just linux), but maybe this weekend I'll be able to install virtual machine. But if you could debug that problem it would be really helpful and I would really appreciate it :-)

**Comment by operatino** [comment]
I haven't tried coffee script before, but I will try :)

**Comment by operatino** [comment]
I fixed it in my fork https://github.com/operatino/node-fs-finder/commit/dca03cd6cd8990816e2d8cd8c14066bbec257e90. I was changing js files directly, you don't have a build script for CoffeeScript in repo? How do I build it? Or you will copy my fix by yourself?
